-- AI Study Planner — Study Experience Migration (Phase 8)
-- Run this in: Supabase Dashboard → SQL Editor → New query

-- 8.3 — track when a topic was completed, for study-streak analytics.
alter table public.plan_items
  add column if not exists completed_at timestamptz;

-- 8.2 — cached condensed exam-mode study guide per topic (generated by Claude).
alter table public.topics
  add column if not exists study_guide text;

-- 8.1 — per-topic "Ask Claude" chat history.
create table if not exists public.chat_messages (
  id         uuid primary key default gen_random_uuid(),
  topic_id   uuid not null references public.topics(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  role       text not null check (role in ('user', 'assistant')),
  content    text not null,
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

create policy "Users can manage their own chat messages"
  on public.chat_messages
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists chat_messages_topic_user_idx
  on public.chat_messages(topic_id, user_id, created_at);
