import Link from "next/link";

export const metadata = { title: "Terms of Service — StudyTool" };

export default function TermsPage() {
  const updated = "8 April 2025";

  return (
    <main className="max-w-2xl mx-auto px-6 py-16 text-slate-700">
      <Link href="/" className="text-sm text-slate-400 hover:text-slate-700 transition-colors mb-8 inline-block">
        ← Back to StudyTool
      </Link>

      <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-slate-400 mb-10">Last updated: {updated}</p>

      <div className="flex flex-col gap-8 text-sm leading-relaxed">
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">1. Acceptance</h2>
          <p className="text-slate-600">
            By creating an account or using StudyTool you agree to these terms. If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">2. Description of service</h2>
          <p className="text-slate-600">
            StudyTool is an AI-assisted study planning tool. You upload PDF study material, and the service generates a day-by-day study schedule based on the extracted topics and your exam date.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">3. Accounts</h2>
          <ul className="list-disc pl-5 flex flex-col gap-1.5 text-slate-600">
            <li>You must be at least 16 years old to use StudyTool.</li>
            <li>You are responsible for keeping your login credentials secure.</li>
            <li>One account per person. Do not share accounts.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">4. Free and Premium plans</h2>
          <ul className="list-disc pl-5 flex flex-col gap-1.5 text-slate-600">
            <li>The Free plan is subject to usage limits (courses, PDFs, plans) as described on the <Link href="/account" className="text-indigo-600 hover:underline">Account</Link> page.</li>
            <li>Premium subscriptions are billed monthly at €8. You can cancel at any time via the billing portal; cancellation takes effect at the end of the billing period.</li>
            <li>We reserve the right to change pricing with 30 days notice to existing subscribers.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">5. Your content</h2>
          <p className="text-slate-600">
            You retain ownership of any PDFs and study material you upload. You grant us a limited licence to process this content solely to provide the service. You confirm you have the right to upload and process the content you submit.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">6. Acceptable use</h2>
          <p className="text-slate-600 mb-2">You must not:</p>
          <ul className="list-disc pl-5 flex flex-col gap-1.5 text-slate-600">
            <li>Upload content that infringes third-party intellectual property rights.</li>
            <li>Attempt to bypass plan limits or rate limiting.</li>
            <li>Use the service in any way that could harm, disable, or impair it.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">7. AI-generated content</h2>
          <p className="text-slate-600">
            Topic extractions and study schedules are generated by AI and may contain errors. StudyTool does not guarantee the accuracy or completeness of AI-generated content. Always verify important study material independently.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">8. Limitation of liability</h2>
          <p className="text-slate-600">
            StudyTool is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including any impact on your academic results.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">9. Termination</h2>
          <p className="text-slate-600">
            You may delete your account at any time from your <Link href="/account" className="text-indigo-600 hover:underline">Account</Link> page. We reserve the right to suspend or terminate accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">10. Governing law</h2>
          <p className="text-slate-600">
            These terms are governed by Dutch law. Any disputes shall be subject to the exclusive jurisdiction of the courts of Amsterdam, the Netherlands.
          </p>
        </section>
      </div>
    </main>
  );
}
